project:
  type: book
license: CC BY-SA
latex-auto-install: true

lang: en
book:
  title: "Animated interactive data visualization using animint2 in R"
  repo-url: https://github.com/animint/animint-manual-en
  repo-actions: [edit, issue, source]
  repo-subdir: chapters
  favicon: Figures/favicon.ico
  cover-image: Figures/logo.png
  downloads: [pdf]
  sidebar:
    style: "docked"
    collapse-level: 2
    border: true
    search: true
  page-footer:
    left: |
      All content licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) <br> &copy; [Toby Dylan Hocking](https://tdhock.github.io).
    center: "[GitHub](https://github.com/animint/animint2) | [Gallery](https://animint.github.io/gallery)"
    right: Built with [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  chapters:
    - index.qmd
    - part: "animint2 basics"
      chapters:
        - Ch02/index.qmd
        - Ch03/index.qmd
        - Ch04/index.qmd
        - Ch05/index.qmd
        - Ch06/index.qmd
        - Ch07/index.qmd
    - part: "Advanced examples"
      chapters:
        - Ch08/index.qmd
        - Ch09/index.qmd
        - Ch10/index.qmd
        - Ch11/index.qmd
        - Ch12/index.qmd
        - Ch13/index.qmd
        - Ch14/index.qmd
        - Ch15/index.qmd
        - Ch16/index.qmd
        - Ch17/index.qmd
        - Ch18/index.qmd
  appendices:
    - Ch99/index.qmd
    - contribute.qmd

bibliography: refs.bib

format:
  html:
    theme:
      light: [default]
    page-layout: full
    fontsize: "15px"
    linestretch: 1.6
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral

  # see https://pandoc.org/MANUAL.html for all options
  pdf:
    documentclass: style/krantz
    classoption: krantz2
    lof: false
    lot: false
    toc: false
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: top
    urlcolor: "blue"
    linkcolor: "black"
    biblio-style: apalike
    keep-tex: true
    code-block-bg: "#f2f2f2"
    code-block-border-left: "#f2f2f2"
    code-overflow: wrap
    mermaid:
      theme: neutral
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

knitr:
  opts_chunk:
    cache: false
    dpi: 100
    fig.width: 8
    fig.height: 5
    out.width: "100%"
    split: true
    R.options:
      animint2.chromote_sleep_seconds: 3
      width: 80
      datatable.print.nrows: 10
      datatable.print.topn: 2
      datatable.print.class: false
      datatable.print.keys: false
      datatable.print.trunc.cols: false
