on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build-book

jobs:
  build-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Render book
        run: R --vanilla < render.R

      - name: netlify deploy
        uses: animint/animint-actions/netlify-deploy-comment@main
        with:
          netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify_site_id: ${{ secrets.NETLIFY_SITE_ID }}
          pat_github_pr: ${{ secrets.PAT_GITHUB_PR }}
          path: chapters/_book
          netlify_url: animint-manual-en.netlify.app
