on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Check width

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: knitr
      - name: Test width
        run: R --vanilla < test-width.R
